---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mantl-site
  namespace: mantl-site
  labels:
    name: mantl-site
spec:
  replicas: 5
  template:
    metadata:
      name: mantl-site
      labels:
        name: mantl-site
    spec:
      containers:
        - name: mantl-site
          image: trxuk/mantlio:10.0
          imagePullPolicy: Always
          ports:
            - name: mantl-http
              containerPort: 80

